# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MzZjMmE4OWUwNDJlN2RiYjA3OWNlZDhlY2M4NzcwN2M2NTZiYWVmZmEyMTIzMmEwYzg3YjFhMzllMzk1MTYzNWM2MmFlZWI1ZDZhNzhiYWZiOWU0YjczZDYzZDcyYWQwMmUxOTY3ZTdjNDFiNjYzYTgwZmRmZTgzMDQxMDg2MWE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
